# Define API specification here

swagger: "2.0"
info:
  title: User API
  version: "1.0.0"
paths:
  /auth/register:
    post:
      # For dropdown
      tags:
        # List for multiple
        - Authentication
      summary: User Registration
      description: Registers a new user with provided credentials.
      parameters:
        # list of parameter objects
        - name: body
          in: body
          description: User registration details
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: User's name
              email:
                type: string
                format: email
                description: User's email address
              password:
                type: string
                description: User's password
      responses:
        201:
          description: User registered successfully
        400:
          description: Bad request
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
        409:
          description: User already exists
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
