# Define API specification here

openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retrieve a greeting message
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
