# Define API specification here

swagger: "2.0"
info:
  title: User API - Live Documentation
  version: "1.0.0"
paths:
  /auth/register:
    post:
      # For dropdown
      tags:
        # List for multiple
        - Authentication
      summary: User Registration
      description: Register a new user with provided credentials.
      parameters:
        # list of parameter objects
        - name: body
          in: body
          description: User registration details
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: User's name
                example: Test User
              email:
                type: string
                format: email
                description: User's email address
                example: test@test.com
              password:
                type: string
                description: User's password
                example: password123
      responses:
        201:
          description: User registered successfully
        400:
          description: Bad request
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: Invalid request body
        409:
          description: User already exists
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: User already exists
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: Internal server error
  /auth/login:
    post:
      tags:
        - Authentication
      summary: User Login
      description: Login a registered user and obtain JWT access token
      parameters:
        - name: body
          in: body
          description: User login details
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                description: User's email address
                example: test@test.com
              password:
                type: string
                description: User's password
                example: password123
      responses:
        200:
          description: Successfully logged in
          schema:
            type: object
            properties:
              token:
                type: string
                description: JWT token for logged-in user
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNjM0NzU0MDAwLCJleHAiOjE2MzQ3NTQwNDF9.QHd3TcbxhXU5TgFwQ0TVtW5W8H4tT7dUyvRcHVlguNA
        400:
          description: Bad request
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: Invalid request body
        401:
          description: Unauthorized
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: Invalid password
        404:
          description: User not found
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: User not found
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: Internal server error
  /users/:
    get:
      tags:
        - Users
      summary: Get all users
      description: Retrieve id, name, and email detail for all users. Requires authorization with login token.
      security:
        - BearerAuth: []
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: User ID
                  example: 1
                name:
                  type: string
                  description: User's name
                  example: Test User
                email:
                  type: string
                  description: User's email address
                  example: test@test.com
        401:
          description: Unauthorized
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: Unauthorized
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message
                example: Internal server error
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Bearer authentication token (include 'BEARER ' prefix and a space before the token)
